<a href="https://colab.research.google.com/github/JaimePablo/matematicas/blob/main/practicas/practica_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Práctica 3. Álgebra
* Para aprender sobre Python vea la playlist [Python para Matemáticas](https://www.youtube.com/playlist?list=PL8gpDXwO-9l4HkDJ9QhB4H-cOiT0BYGau)
* Para obtener ideas y vídeos para la resolución de la práctica vea los archivos siguientes: [Ideas](https://github.com/financieras/math/tree/main/ideas)

## Práctica 3.1
**Determinante en Excel**  

* Cree un fichero en Excel de nombre algebra.xlsm.
* La extensión **xlsm** corresponde a los archivos de Excel habilitados para macros.
* Utilice la Hoja 1 para hacer la Práctica 3.1.
* Se pide:
 1. Cree una matriz cuadrada de dimensión 5×5, formada por números aleatorios enteros entre -9 y +9.
 2. Calcule el determinante de esta matriz
 3. Cree un programa en **VBA** que busque una matriz de este tipo cuyo determinante sea cero.
 4. Copie la matriz encontrada y péguela debajo con "pegado especial valores" para que no varíe su contenido al efectuar el recálculo manual de la hoja.

## Práctica 3.2
**Matriz inversa en Excel**  

* Use el mismo archivo de Excel con extensión **xlsm** del caso anterior. 
* Utilice la Hoja 2 para hacer la Práctica 3.2.
* Se pide:
 1. Crea la matriz $A$ que es una matriz cuadrada de dimensiones 5×5 usando números aleatorios enteros entre -9 y +9, excepto cero
 2. Calcule su determinante
 3. Calcule su transpuesta usando la función ```TRANSPONER```
 4. Calcule su matriz inversa $A^{-1}$
 5. Multiplique la matriz $A$ por su inversa $A^{-1}$ y compruebe que el producto es la matriz identidad.
 $$AA^{-1}=I$$

## Práctica 3.3
**Resolución de sistemas lineales en Excel**  

* Use el mismo archivo de Excel con extensión **xlsm** del caso anterior. 
* Utilice la Hoja 3 para hacer la Práctica 3.3.
* Se pide:
 1. Cree un sistema de 5 ecuaciones con 5 incógnitas con **solución única**.
 2. Una de las ecuaciones será: $\quad x_1+2x_2-x_3+x_4-3x_5=6$
 3. Muestre las ecuaciones del sistema usando el [editor de ecuaciones](https://support.microsoft.com/es-es/office/editor-de-ecuaciones-6eac7d71-3c74-437b-80d3-c7dea24fdf3f) de Excel. $\quad Ax=b$
 4. Monte la matriz $A$ del sistema de ecuaciones y la matriz $b$ con los términos independientes. Muestre ambas matrices.
 5. Calcule la matriz inversa $A^{-1}$
 6. Resuelva el sistema lineal de ecuaciones con este método: $\quad Ax=b \quad \Longrightarrow \quad x=A^{-1}b$
 7. Compruebe si el resultado obtenido es la solución del sistema de ecuaciones. Justifique esa comprobación.

## Práctica 3.4
**Matriz inversa en Python**  

Desarrolla un código en Python que al ejecutarse consiga los siguientes apartados.  
1. Crea una matriz cuadrada de dimensiones 3×3 usando números aleatorios enteros entre -9 y +9, excepto cero
2. Buscar un caso donde el determinante sea igual a 1
3. Si el determinante es 1 imprime la matriz y su determinante
4. Calcula e imprime su transpuesta
5. Calcula e imprime su matriz inversa
6. Multiplica la matriz creada por su inversa y comprueba que el producto es la matriz identidad.
7. Calcula cuantos segundos ha tardado en realizarse el proceso.

In [21]:
import numpy as np

n = 5  

while True:
    m = np.random.randint(-9,9, size=(3, 3) )  
    determ = np.linalg.det(m)
    if determ == 1:
        print(m)
        break
print()
print(f"El determinante de la matriz es {determ}")
print()

print("Matriz:")
print(m)
print()

print("\nTranspuesta:")
print(np.transpose(m))
print()

print("Inversa:")
minv = np.linalg.inv(m)
print(minv)
print()

print("Identidad: ")
print(m @ minv)           
print()

from time import process_time

t1 = process_time()

for i in range(10_000_000):
    cuadrado = i**2

t2 = process_time()
print(f"El proceso ha tardado {t2-t1} segundos.")


[[ 2  4 -7]
 [-2 -5  7]
 [ 1  2 -4]]

El determinante de la matriz es 1.0

Matriz:
[[ 2  4 -7]
 [-2 -5  7]
 [ 1  2 -4]]


Transpuesta:
[[ 2 -2  1]
 [ 4 -5  2]
 [-7  7 -4]]

Inversa:
[[ 6.  2. -7.]
 [-1. -1. -0.]
 [ 1. -0. -2.]]

Identidad: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

El proceso ha tardado 3.4633874959999993 segundos.


## Práctica 3.5
**Resolución de sistemas lineales en Python**  

1. Cree un sistema de 4 ecuaciones con 4 incógnitas con **solución única**.
2. La solución del sistema es: $\; \begin{pmatrix}x_1, x_2, x_3, x_4\end{pmatrix} = \begin{pmatrix} 3, 4, 5, 2\end{pmatrix}$  
3. Una de las ecuaciones del sistema es: $\enspace x_1+3x_2-x_3-2x_4=6$  
4. El vector $b$ de términos independientes es: $\enspace b=\begin{pmatrix}6, 3, 5, 7\end{pmatrix}$  
5. Usando números aleatorios elija los coeficientes que faltan de la matriz $A$ del sistema de ecuaciones.
  - Los coeficientes deben ser números enteros entre -5 y +5, excluido el cero.
  - Imprima la matriz $A$.  
6. Calcule e imprima el determinante de $A$.
7. Calcule e imprima la matriz inversa $A^{-1}$  
8. Resuelva el sistema lineal de ecuaciones con este método: $$Ax=b \quad \Longrightarrow \quad x=A^{-1}b$$
9. Compruebe que el resultado obtenido es la solución del sistema de ecuaciones.  
10. Resuelva nuevamente el sistema de ecuaciones usando ```np.linalg.solve```.

In [16]:
import numpy as np

v = np.array([3,4,5,2])   

def busca(b):
    while True:
        w = np.random.choice(list(range(-5,0)) + list(range(1,6)), 4)
        if np.matmul(v, w) == b:   
            break
    return w

b =  6; print(f"{busca(b)} x {v} = {b}")
b = 3; print(f"{busca(b)} x {v} = {b}")
b = 5; print(f"{busca(b)} x {v} = {b}")
b = 7; print(f"{busca(b)} x {v} = {b}")


[ 1  4 -1 -4] x [3 4 5 2] = 6
[ 1 -2  2 -1] x [3 4 5 2] = 3
[-4  2  1  2] x [3 4 5 2] = 5
[ 2  5 -3 -2] x [3 4 5 2] = 7


In [29]:
import numpy as np

f1 = [1, 3, -1,  -2]
f2 = [3, -5,  4, -3]
f3 = [1, -5, 4,  1]
f4 = [-2,  1, 1, 2]
matriz = [f1, f2, f3, f4]
print(matriz)
print()

m = np.array(matriz)
print("Matriz:")
print(m)
print()

determ = np.linalg.det(m)
print()
print(f"El determinante de la matriz es {determ}")
print()
print("Inversa:")
minv = np.linalg.inv(m)
print(minv)
print()

print("X: ")
sist = minv @[ 6,3,5,7]
print(sist)
print()

[[1, 3, -1, -2], [3, -5, 4, -3], [1, -5, 4, 1], [-2, 1, 1, 2]]

Matriz:
[[ 1  3 -1 -2]
 [ 3 -5  4 -3]
 [ 1 -5  4  1]
 [-2  1  1  2]]


El determinante de la matriz es 52.00000000000001

Inversa:
[[ 0.69230769 -0.53846154  0.84615385 -0.53846154]
 [ 0.42307692 -0.13461538  0.21153846  0.11538462]
 [ 0.26923077  0.09615385  0.13461538  0.34615385]
 [ 0.34615385 -0.51923077  0.67307692 -0.26923077]]

X: 
[3. 4. 5. 2.]



In [13]:
import numpy as np
a = np.array([[1,3,-1,-2], [3,-5,4,-3], [1,-5,4,1], [-2,1,1,2]])
b = np.array([6,3,5,7])
a_inv = np.linalg.inv(a)
np.dot(a_inv, b)

array([3., 4., 5., 2.])

## Práctica 3.6
**Resolución de sistemas lineales con Octave**  

1. Tome el mismo sistema 4x4 con solución única del ejercicio anterior.
2. Muestra el sistema usando $\LaTeX$
3. Resuélvelo con Octave por dos métodos
4. ¿Ambos métodos dan el mismo resultado?



$$
\left.
\begin{array}{rrrcr}
  1x &+3y &-z &-2w &= &6 \\
  3x &-5y &+4z &-3w &= &3 \\
  1x &-5y &+4z&+w &= &5 \\
  -2x &+y &+z &+2w &= &7
\end{array}
\right\}$$

* Forma matricial:

$$Ax = b$$

* Despejamos la $x$:
$$x = A^{-1}b$$

* Desarrollo de matrices:
$$\left( \begin{array}{rrrr}
     1 & 3 & -1 & -2 \\
     3 & -5 & 4 & -3 \\
    1 & -5 & 4 &  1 \\
     -2 &1 & 1 & 2
  \end{array}\right) \begin{pmatrix}
  x \\
  y \\
  z \\
  w
\end{pmatrix} = \begin{pmatrix}
  6 \\
  3 \\
  5 \\
  7
\end{pmatrix}$$

* Se despeja el vector:

$$\begin{pmatrix}
  x \\
  y \\
  z \\
  w
\end{pmatrix} = 
\left( \begin{array}{rrrr}
  1 & 3 & -1 & -2 \\
     3 & -5 & 4 & -3 \\
    1 & -5 & 4 &  1 \\
     -2 &1 & 1 & 2
  \end{array}\right)  ^{-1} \begin{pmatrix}
  6 \\
  3 \\
  5 \\
  7
\end{pmatrix}$$

* Se calcula la inversa:


$$\begin{pmatrix}
  x \\
  y \\
  z \\
  w
\end{pmatrix} = 
\left( \begin{array}{rrrr}
     \frac{9}{13} & \frac{-7}{13} & \frac{11}{13} &  \frac{-7}{13} \\
     \frac{11}{26} & \frac{-7}{52} & \frac{11}{52} & \frac{3}{26} \\
     \frac{7}{26} & \frac{5}{52} & \frac{7}{52} & \frac{9}{26} \\
     \frac{9}{26} & \frac{-27}{52} & \frac{35}{52} & \frac{-7}{26}
  \end{array}\right) \begin{pmatrix}
  6 \\
  3 \\
  5 \\
  7
\end{pmatrix}$$


* Obtenemos de solución:

$$\begin{pmatrix}
  x \\
  y \\
  z \\
  w
\end{pmatrix} = \begin{pmatrix}
  3 \\
  4 \\
  5 \\
  2
\end{pmatrix}$$


In [ ]:
#Método 1
!apt update
!apt install octave


In [9]:

%%writefile primero.m
A = [1 3 -1 -2; 3 -5 4 -3; 1 -5 4 1 ; -2 1 1 2]
b = [6; 3; 5; 7]
x= inv(A)*b
% solución 1
s1 =rats(x)


Overwriting primero.m


In [ ]:
!octave primero.m

In [ ]:
#Método 2
!apt update
!apt install octave 


In [ ]:
%%writefile segundo.m
G = [1 3 -1 -2 6; 3 -5 4 -3 3; 1 -5 4 1 5; 4 -3 -3 11 7]
escalonada = rref(G)
% solución 2
s2 = rats(escalonada)

In [ ]:
!octave segundo.m

Con ambos métodos obtenemos el mismo resultado


## Práctica 3.7
**Diagonalización en Python**

* Sea la matriz cuadrada $A$ de orden 4x4

$$A=\left(
\begin{array}{rrrr}
 -1 &-2 &  3 &-1 \\
  0 & 2 &  0 & 0 \\
  0 & 0 &  2 & 0 \\
  0 & 0 &  0 & 1
\end{array}
\right)$$
1. Calcula los **autovalores** y **autovectores**
2. Calcula y muestra:
 - la matriz diagonal $D$
 - la matriz de paso $P$
 - su inversa $P^{-1}$  
3. Comprueba que se cumple que $A^3=PD^3P^{-1}$

In [ ]:
import numpy as np
A = np.array([[-1,-2,3,-1], [0,2,0,0], [0,0,2,0], [0,0,0,1]])
d,P = np.linalg.eig(A)
print("d: ", d)
D = np.diag(d)
print("\nD:\n", D)
print("\nP:\n", P)

In [ ]:
import numpy as np
A = np.array([[-1,-2,3,-1], [0,2,0,0], [0,0,2,0], [0,0,0,1]])
print(A@A@A)

In [ ]:
import numpy as np
A = np.array([[-1,-2,3,-1], [0,2,0,0], [0,0,2,0], [0,0,0,1]])
d,P = np.linalg.eig(A)
print("d: ", d)
D = np.diag(d)
print("\nD:\n", D)
print("\nP:\n", P)
Dcubo = D @ D @ D
print("\nDcubo:\n", Dcubo)
print("\nSolución:\n", P @ Dcubo @ np.linalg.inv(P))

## Práctica 3.8
**Diagonalización con Octave**

Resuelva el ejercicio anterior, pero en esta ocasión utilizando Octave.

In [ ]:
!apt update
!apt install octave

In [ ]:
%%writefile diagonaliza.m
A = [-1,-2,3,-1; 0,2,0,0; 0,0,2,0; 0,0,0,1]
[P,D]=eig(A)
Dcubo = D^3
Acubo = A^3
PxDcuboXPinv = P*Dcubo*P^-1

In [ ]:
!octave diagonaliza.m

## Práctica 3.9
**Libertad para elegir el lugar de trabajo**  
Resolver con **Octave**.

Una empresa de 1.000 empleados permite que sus trabajadores cada día acudan a trabajar a la oficina o que realicen su trabajo desde su casa. Inicialmente el 90% de la plantilla trabajaba en la oficina y solo el 10% lo hacían en casa. Se ha observado que los que un día trabajan en casa tienen una probabilidad del 70% de realizarlo también desde casa al día siguiente, pero que en el restante 30% de los casos acuden a la oficina al día siguiente. Por el contrario, se ha observado que los que un día trabajaron en la oficina al día siguiente vuelven
a la oficina en el 60% de los casos y en el 40% restante van a su casa al día siguiente.
* Determinar qué número de empleados se quedan en casa transcurridos dos días.
* ¿Y a largo plazo cuantos se quedan en casa?

In [ ]:
!apt update
!apt install octave

In [ ]:
%%writefile proceso.m
empleados = 1000
% state vector
inicial = [.9; .1]
% transition probability matrix
A = [.6, .3; .4, .7]
[P,D]=eig(A)
Dcuadrado = D^2
Acuadrado = A^2
PxDcuadradoXPinv = P*Dcuadrado*P^-1
dia2 = Acuadrado * inicial
disp("Nº de empleados que se quedan en casa el segundo día: "), disp(dia2(2)*empleados)
D10 = D^10
A10 = P*D10*P^-1
dia10 = A10 * inicial
disp("Nº de empleados que se quedan en casa a largo plazo son: "), disp(dia10(2)*empleados)

In [ ]:
!octave proceso.m

## Práctica 3.10
**Tendencia del mercado**  
Resolver con **Python**.

En el mercado de automóviles de gran lujo únicamente se disputan la clientela dos marcas (A y B). Las ventas son $M=100.000$ automóviles anuales, no variando esta cifra con el transcurso de los años. La marca A es líder de mercado en este momento con el 75% de las ventas. Sus directivos desean consolidar su liderazgo e incluso aumentarlo, para lo cual todos los años efectúan una fuerte campaña publicitaria con la que consiguen cada año un 40% de los que fueron clientes de su competidora, aunque la empresa A pierde un 20% de sus clientes que se van a la competencia.
* ¿Cuál es la situación a los 3 años?
* ¿Y al cabo de mucho tiempo?

In [1]:
import numpy as np

X0 = np.array([.75, .25])
A = np.array([[.8, .4], [.2 ,.6]])
X3 = A@A@A@X0
print("Situación a los tres años:", X3)

d,P = np.linalg.eig(A)
D = np.diag(d)
Pinv = np.linalg.inv(P)

print("Situación a los cincuenta años:", P@(D**50)@Pinv@X0)

Situación a los tres años: [0.672 0.328]
Situación a los cincuenta años: [0.66666667 0.33333333]
